import type { Metadata } from 'next'
import Link from 'next/link'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const footerLinks = [
  {
    "text": "Sign Up",
    "href": "/reg"
  },
  {
    "text": "Log in",
    "href": "/login"
  },
  {
    "text": "Messenger",
    "href": ""
  },
  {
    "text": "Facebook Lite",
    "href": ""
  },
  {
    "text": "Video",
    "href": ""
  },
  {
    "text": "Places",
    "href": ""
  },
  {
    "text": "Games",
    "href": ""
  },
  {
    "text": "Marketplace",
    "href": ""
  },
  {
    "text": "Meta Pay",
    "href": ""
  },
  {
    "text": "Meta Store",
    "href": ""
  },
  {
    "text": "Meta Quest",
    "href": ""
  },
  {
    "text": "Instagram",
    "href": ""
  },
  {
    "text": "Threads",
    "href": ""
  },
  {
    "text": "Fundraisers",
    "href": ""
  },
  {
    "text": "Services",
    "href": ""
  },
  {
    "text": "Voting Information Centre",
    "href": ""
  },
  {
    "text": "Privacy Policy",
    "href": ""
  },
  {
    "text": "Privacy Centre",
    "href": ""
  },
  {
    "text": "Groups",
    "href": ""
  },
  {
    "text": "About",
    "href": ""
  },
  {
    "text": "Create ad",
    "href": ""
  },
  {
    "text": "Create Page",
    "href": ""
  },
  {
    "text": "Developers",
    "href": ""
  },
  {
    "text": "Careers",
    "href": ""
  },
  {
    "text": "Cookies",
    "href": ""
  },
  {
    "text": "AdChoices",
    "href": ""
  },
  {
    "text": "Terms",
    "href": ""
  },
  {
    "text": "Help",
    "href": ""
  },
  {
    "text": "Contact uploading and non-users",
    "href": ""
  },
  {
    "text": "Settings",
    "href": ""
  },
  {
    "text": "Activity log",
    "href": ""
  }
]
export default function AccountLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div data-test_id="account_layout" className="min-h-screen flex flex-col bg-[#F0F2F5]">
      {children}

      <footer className="bg-white px-5 pb-8">
        <div className="max-w-4xl m-auto">
          <hr className="my-3" />
          <div className="flex flex-wrap text-xs text-[#385898] whitespace-nowrap">
            {footerLinks.map(item => <Link key={item.text} className="mr-5 hover:underline py-0.5" href={item.href}>{item.text}</Link>)}
          </div>
        </div>
      </footer>
    </div>
  )
}
